meta_title: "Halfway"
meta_description: "You and your friend live in two different cities? Find the best flight deals to meet halfway"
meta_image: "halfway_meta_image.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@halfway_ninja" # indispensable pour les Twitter Cards

